version: '3.7'

services:
  dbtest:
    image: postgis/postgis:13-3.1
    ports:
      - "27901:5432"
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=test
      - POSTGRES_DB=sherpa-test
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
