FROM python:3-slim

# Run as a normal user to avoid clobbering system packages
RUN useradd -m -d /home/appuser appuser
USER appuser
WORKDIR /app

ENV PATH=/home/appuser/.local/bin:$PATH \
    # No buffering of output
    PYTHONUNBUFFERED=1                  \
    # Prevent writing some files to reduce image size
    PYTHONDONTWRITEBYTECODE=1           \
    PIP_NO_CACHE_DIR=1                  \
    # pip display options
    PIP_PROGRESS_BAR=off                \
    PIP_NO_COLOR=1                      \
    PIP_DISABLE_PIP_VERSION_CHECK=1     \
    # Install pip packages as regular user
    PIP_USER=1

COPY --chown=appuser requirements.test.txt /tmp/requirements.txt

RUN --mount=type=cache,target=/home/appuser/.cache/pip pip install --user -r /tmp/requirements.txt \
    && rm /tmp/requirements.txt

CMD ["python", "-m", "pytest", "tests", "-vvv", "-p", "no:cacheprovider"]

COPY --chown=appuser . .
