[tool.poetry]
name = "sherpa"
version = "0.1.0"
description = "A CLI tool for loading GIS files to a PostGIS database"
license = "MIT"
authors = ["Connor <contact@kyoh.run>"]
readme = "README.md"
repository = "https://github.com/kyoh-dev/sherpa"

[tool.poetry.dependencies]
python = "^3.9"
psycopg2-binary = "2.9.3"

[tool.poetry.group.dev.dependencies]
mypy = "^0.961"
autoflake = "^1.4"
black = "^22.6.0"

[tool.poetry.group.test.dependencies]
pytest = "^7.1.2"

[tool.poetry.scripts]
sherpa = "sherpa.__main__:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.mypy]
strict = true
install_types = true
non_interactive = true
ignore_missing_imports = true
show_error_codes = true

[tool.black]
line-length = 88
target-version = ['py39']
